"""add passenger_name

Revision ID: 9d0c23cd1f5d
Revises: 
Create Date: 2026-02-19 01:50:22.894794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0c23cd1f5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    op.drop_table('seat_locks')
    op.drop_index(op.f('ix_bookings_airline_code'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_reference'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_created_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_destination'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_pnr'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_seat'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_start'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.create_table('bookings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pnr', sa.VARCHAR(), nullable=False),
    sa.Column('booking_reference', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('start', sa.VARCHAR(), nullable=False),
    sa.Column('destination', sa.VARCHAR(), nullable=False),
    sa.Column('airline_code', sa.VARCHAR(), nullable=False),
    sa.Column('flight_class', sa.VARCHAR(), nullable=False),
    sa.Column('trip_type', sa.VARCHAR(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('return_date', sa.DATE(), nullable=True),
    sa.Column('adults', sa.INTEGER(), nullable=True),
    sa.Column('children', sa.INTEGER(), nullable=True),
    sa.Column('seat', sa.VARCHAR(), nullable=True),
    sa.Column('aircraft_code', sa.VARCHAR(), nullable=True),
    sa.Column('seat_status', sa.VARCHAR(), nullable=True),
    sa.Column('total_amount', sa.INTEGER(), nullable=False),
    sa.Column('payment_status', sa.VARCHAR(), nullable=True),
    sa.Column('razorpay_order_id', sa.VARCHAR(), nullable=True),
    sa.Column('razorpay_payment_id', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_start'), 'bookings', ['start'], unique=False)
    op.create_index(op.f('ix_bookings_seat'), 'bookings', ['seat'], unique=False)
    op.create_index(op.f('ix_bookings_pnr'), 'bookings', ['pnr'], unique=1)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_destination'), 'bookings', ['destination'], unique=False)
    op.create_index(op.f('ix_bookings_date'), 'bookings', ['date'], unique=False)
    op.create_index(op.f('ix_bookings_created_at'), 'bookings', ['created_at'], unique=False)
    op.create_index(op.f('ix_bookings_booking_reference'), 'bookings', ['booking_reference'], unique=1)
    op.create_index(op.f('ix_bookings_airline_code'), 'bookings', ['airline_code'], unique=False)
    op.create_table('seat_locks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('booking_id', sa.INTEGER(), nullable=True),
    sa.Column('seat', sa.VARCHAR(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=1)
    # ### end Alembic commands ###
